version: '3'

services:
  backend:
    image: 23082018/rest-api
    container_name: service
    restart: on-failure
    depends_on:
      - db
    networks:
      - default
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=passengers_db
      - DATABASE_PORT=3306
    ports:
    - 8282:8080


  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: passengers_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - "/src/main/resources/init.sql:/docker-entrypoint-initdb.d/"
    networks:
      - default
    ports:
      - 3306:3306


networks:
  default:
    external:
      name: my-network


