version: '3.7'
services:
  db:
    image: mysql
    container_name: mysqldb
    restart: always
    volumes:
      - "/src/main/resources/init.sql:/docker-entrypoint-initdb.d/"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=passengers_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    ports:
    - 5432:5432

  service:
    image: 23082018/rest-api
    container_name: service
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=passengers_db
      - DATABASE_PORT=5432



