version: '3'

networks:
  default:
    external:
      name: my-network

services:
  backend:
    image: 23082018/my-api
    depends_on:
      - db
    container_name: my-api
    ports:
      - "8080:8080"
    networks:
      - default

  flyway-service-i:
    image: boxfuse/flyway
    command: -url=jdbc:mysql://mysqldb:3306 -schemas=tpassengers_db -user=... -password=... migrate
    volumes:
      - "../resources/db/migration:/flyway/sql"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: passengers_db
      MYSQL_USER:
      MYSQL_PASSWORD:
    networks:
      - default