version: '3'

networks:
  my-network:

services:
  backend:
    image: 23082018/my-api
    depends_on:
      - db
    container_name: my-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/passengers_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - my-network

  flyway:
    image: boxfuse/flyway:5.2.4
    container_name: flyway
    command: -url=jdbc:mysql://mysqldb -schemas=passengers_db -user=root -password=admin -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "/src/main/resources/init.sql:/docker-entrypoint-initdb.d/"
    ports:
      - 3307:3306
    networks:
      - my-network




