version: '3'

networks:
  default:
    external:
      name: my-network

services:
  backend:
    image: 23082018/my-api:latest
    container_name: service
    restart: on-failure
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: passengers_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - "/src/main/resources/init.sql:/docker-entrypoint-initdb.d/"
    networks:
      - default




