INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(100, 'ECONOM', 1, 1);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUE(150, 'BUSINESS', 2, 1);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(100, 'ECONOM', 3, 1);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(100, 'ECONOM', 4, 2);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(150, 'BUSINESS', 5, 2);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(150, 'BUSINESS', 6, 2);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(150, 'BUSINESS', 7, 2);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(150, 'BUSINESS', 8, 3);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(150, 'BUSINESS', 9, 3);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(80, 'ECONOM', 10, 3);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(80, 'ECONOM', 11, 4);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(80, 'ECONOM', 12, 4);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(110, 'BUSINESS', 13, 4);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(110, 'BUSINESS', 14, 5);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(110, 'BUSINESS', 15, 5);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(80, 'ECONOM', 16, 5);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(80, 'ECONOM', 17, 6);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(110, 'BUSINESS', 18, 6);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(80, 'ECONOM', 19, 6);
INSERT INTO TICKETS(TICKET_PRICE, TICKET_TYPE, PASSENGER_ID, ROUTE_ID) VALUES(80, 'ECONOM', 20, 6);


